### ISSUE TITLE
Return status 400 instead of 500 on password validation error

### ISSUE THREAD

**Issue by ent3r** [darkboxapp/backend#5]
As can be seen in the following image, the server returns a 500 error when a password validation error occurs.

![Image of bug](https://images-ext-2.discordapp.net/external/EW20inBmxasSXKXVQ-NneTLtyISNiXlsulgNbL70ktM/%3F_raw%3Dtrue/https/get.banned.today/2msjDka.png?width=908&height=475)

A 400 status code indicates that the client request couldn't be processed due to an error in the request.
> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

A 500 status indicates that an internal server error occured, i.e. a bug in the server's logic.
> The server encountered an unexpected condition that prevented it from fulfilling the request.

While a 500 could work, a 400 would be better as it tells the client that *it* had the issue and needs to change the input, and not that *the server* has an issue that the client cannot fix.

**Comment by xpyxel** [comment]
I changed the error codes accordingly in commit f08f70ceb6c7d89ba96e35b58764ea2e4aa766b8, thanks for the issue!
